;(function(window){'use strict';var bodyEl=document.body,docElem=window.document.documentElement,support={transitions:Modernizr.csstransitions},transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[Modernizr.prefixed('transition')],onEndTransition=function(el,callback){var onEndCallbackFn=function(ev){if(support.transitions){if(ev.target!=this)return;this.removeEventListener(transEndEventName,onEndCallbackFn);}
if(callback&&typeof callback==='function'){callback.call(this);}};if(support.transitions){el.addEventListener(transEndEventName,onEndCallbackFn);}
else{onEndCallbackFn();}},win={width:window.innerWidth,height:window.innerHeight},lockScroll=false,xscroll,yscroll,scrollContainer=document.querySelector('.container'),sliderEl=document.querySelector('.slider'),items=[].slice.call(sliderEl.querySelectorAll('.slide')),itemsTotal=items.length,navRightCtrl=sliderEl.querySelector('.button--nav-next'),navLeftCtrl=sliderEl.querySelector('.button--nav-prev'),zoomCtrl=sliderEl.querySelector('.button--zoom'),contentEl=document.querySelector('.content'),closeContentCtrl=contentEl.querySelector('button.button--close'),current=0,isOpen=false,isFirefox=typeof InstallTrigger!=='undefined',bodyScale=isFirefox?false:3;function scrollX(){return window.pageXOffset||docElem.scrollLeft;}
function scrollY(){return window.pageYOffset||docElem.scrollTop;}
function throttle(fn,delay){var allowSample=true;return function(e){if(allowSample){allowSample=false;setTimeout(function(){allowSample=true;},delay);fn(e);}};}
function init(){initEvents();}
function initEvents(){zoomCtrl.addEventListener('click',function(){openItem(items[current]);});closeContentCtrl.addEventListener('click',closeContent);navRightCtrl.addEventListener('click',function(){navigate('right');});navLeftCtrl.addEventListener('click',function(){navigate('left');});window.addEventListener('resize',throttle(function(ev){win={width:window.innerWidth,height:window.innerHeight};items.forEach(function(item,pos){if(pos===current)return;var el=item.querySelector('.slide__mover');dynamics.css(el,{translateX:el.offsetWidth});});},10));document.addEventListener('keydown',function(ev){if(isOpen)return;var keyCode=ev.keyCode||ev.which;switch(keyCode){case 37:navigate('left');break;case 39:navigate('right');break;}});}
function openItem(item){if(isOpen)return;isOpen=true;var zoomer=item.querySelector('.zoomer');classie.add(zoomer,'zoomer--active');scrollContainer.addEventListener('scroll',noscroll);applyTransforms(zoomer);if(bodyScale){dynamics.animate(bodyEl,{scale:bodyScale},{type:dynamics.easeInOut,duration:500});}
onEndTransition(zoomer,function(){if(bodyScale){dynamics.stop(bodyEl);dynamics.css(bodyEl,{scale:1});bodyEl.style.WebkitTransform='none';bodyEl.style.transform='none';}
classie.add(bodyEl,'noscroll');classie.add(contentEl,'content--open');var contentItem=document.getElementById(item.getAttribute('data-content'))
classie.add(contentItem,'content__item--current');classie.add(contentItem,'content__item--reset');classie.add(zoomer,'zoomer--notrans');zoomer.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';zoomer.style.transform='translate3d(0,0,0) scale3d(1,1,1)';});}
function closeContent(){var contentItem=contentEl.querySelector('.content__item--current'),zoomer=items[current].querySelector('.zoomer');classie.remove(contentEl,'content--open');classie.remove(contentItem,'content__item--current');classie.remove(bodyEl,'noscroll');if(bodyScale){bodyEl.style.WebkitTransform='';bodyEl.style.transform='';}
var nobodyscale=true;applyTransforms(zoomer,nobodyscale);onEndTransition(contentItem,function(ev){classie.remove(this,'content__item--reset');lockScroll=false;scrollContainer.removeEventListener('scroll',noscroll);zoomer.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';zoomer.style.transform='translate3d(0,0,0) scale3d(1,1,1)';applyTransforms(zoomer);setTimeout(function(){classie.remove(zoomer,'zoomer--notrans');classie.remove(zoomer,'zoomer--active');zoomer.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';zoomer.style.transform='translate3d(0,0,0) scale3d(1,1,1)';},25);if(bodyScale){dynamics.css(bodyEl,{scale:bodyScale});dynamics.animate(bodyEl,{scale:1},{type:dynamics.easeInOut,duration:500});}
isOpen=false;});}
function applyTransforms(el,nobodyscale){var zoomerArea=el.querySelector('.zoomer__area'),zoomerAreaSize={width:zoomerArea.offsetWidth,height:zoomerArea.offsetHeight},zoomerOffset=zoomerArea.getBoundingClientRect(),scaleVal=zoomerAreaSize.width/zoomerAreaSize.height<win.width/win.height?win.width/zoomerAreaSize.width:win.height/zoomerAreaSize.height;if(bodyScale&&!nobodyscale){scaleVal/=bodyScale;}
el.style.WebkitTransform='translate3d('+ Number(win.width/2-(zoomerOffset.left+zoomerAreaSize.width/2))+'px,'+ Number(win.height/2-(zoomerOffset.top+zoomerAreaSize.height/2))+'px,0) scale3d('+ scaleVal+','+ scaleVal+',1)';el.style.transform='translate3d('+ Number(win.width/2-(zoomerOffset.left+zoomerAreaSize.width/2))+'px,'+ Number(win.height/2-(zoomerOffset.top+zoomerAreaSize.height/2))+'px,0) scale3d('+ scaleVal+','+ scaleVal+',1)';}
function navigate(dir){var itemCurrent=items[current],currentEl=itemCurrent.querySelector('.slide__mover'),currentTitleEl=itemCurrent.querySelector('.slide__title');if(dir==='right'){current=current<itemsTotal-1?current+ 1:0;}
else{current=current>0?current- 1:itemsTotal-1;}
var itemNext=items[current],nextEl=itemNext.querySelector('.slide__mover'),nextTitleEl=itemNext.querySelector('.slide__title');dynamics.animate(currentEl,{opacity:0,translateX:dir==='right'?-1*currentEl.offsetWidth/2:currentEl.offsetWidth/2,rotateZ:dir==='right'?-10:10},{type:dynamics.spring,duration:2000,friction:600,complete:function(){dynamics.css(itemCurrent,{opacity:0,visibility:'hidden'});}});dynamics.animate(currentTitleEl,{translateX:dir==='right'?-250:250,opacity:0},{type:dynamics.bezier,points:[{"x":0,"y":0,"cp":[{"x":0.2,"y":1}]},{"x":1,"y":1,"cp":[{"x":0.3,"y":1}]}],duration:450});dynamics.css(itemNext,{opacity:1,visibility:'visible'});dynamics.css(nextEl,{opacity:0,translateX:dir==='right'?nextEl.offsetWidth/2:-1*nextEl.offsetWidth/2,rotateZ:dir==='right'?10:-10});dynamics.animate(nextEl,{opacity:1,translateX:0},{type:dynamics.spring,duration:2000,friction:600,complete:function(){items.forEach(function(item){classie.remove(item,'slide--current');});classie.add(itemNext,'slide--current');}});dynamics.css(nextTitleEl,{translateX:dir==='right'?250:-250,opacity:0});dynamics.animate(nextTitleEl,{translateX:0,opacity:1},{type:dynamics.bezier,points:[{"x":0,"y":0,"cp":[{"x":0.2,"y":1}]},{"x":1,"y":1,"cp":[{"x":0.3,"y":1}]}],duration:650});}
function noscroll(){if(!lockScroll){lockScroll=true;xscroll=scrollContainer.scrollLeft;yscroll=scrollContainer.scrollTop;}
scrollContainer.scrollTop=yscroll;scrollContainer.scrollLeft=xscroll;}
init();})(window);